version: "3.8"

services:
  redis:
    container_name: "hayat_redis"
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - hayat_network
  db:
    image: mysql:8.0
    env_file: ./.env
    container_name: "hayat_mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=harera
      - MYSQL_DATABASE=hayat
    ports:
      - "3306:3306"
networks:
  hayat_network:
    driver: bridge
