version: "3.8"

services:
  redis:
    container_name: "hayat_redis"
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - hayat_network
  app:
    container_name: hayat_spring
    build: ./Dockerfile
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
    networks:
      - hayat_network
    depends_on:
      - redis
      - postgres
  postgres:
    image: postgres
    container_name: "hayat_postgres"
    restart: unless-stopped
    env_file: ./.env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_DATABASE}
    ports:
      - ${DB_LOCAL_PORT}:${DB_DOCKER_PORT}
networks:
  hayat_network:
    driver: bridge
