version: "3.8"

services:
  app:
    build: ./Dockerfile
    container_name: "hayat_app"
    image: hayat_app:latest
    ports:
      - 8080:8080
    depends_on:
      - redis
      - db
    networks:
      - hayat_network
  redis:
    container_name: "hayat_redis"
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - hayat_network
#    command: redis-server --requirepass ${REDIS_PASSWORD}
  db:
    image: mysql:8.0
    container_name: "hayat_mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=harera
      - MYSQL_DATABASE=hayat
    hostname: "localhost"
    volumes:
      - hayat_db:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - hayat_network
networks:
  hayat_network:
    driver: bridge
volumes:
  hayat_db: