version: "3.8"

services:
  test_redis:
    container_name: "hayat_redis"
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - hayat_internal_network
  test_db:
    image: mysql:8.0
    container_name: "hayat_test_mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hayat
    ports:
      - "3366:3306"
networks:
  hayat_app_network:
    driver: bridge
  hayat_internal_network:
    driver: bridge
    internal: true
volumes:
  hayat_db: