version: "3.8"

services:
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: "keycloak"
    command:
      - "start-dev"
    ports:
      - "8180:8080"
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KEYCLOAK_IMPORT=/tmp/realm.json
    networks:
      - hayat_app_network
networks:
  hayat_app_network:
    driver: bridge
  hayat_internal_network:
    driver: bridge
    internal: true
volumes:
  hayat_db: