version: "3.8"

services:
  app:
    build: ./Dockerfile
    container_name: hayat_app
    ports:
      - 8080:8080
    networks:
      - hayat_network
    depends_on:
      - redis
      - db
  redis:
    container_name: "hayat_redis"
    image: redis:latest
    ports:
      - "6379:6379"
  db:
    image: mysql:8.0
    env_file: ./.env
    container_name: "hayat_mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=hayat
    ports:
      - "3306:3306"
