version: "3.8"

services:
  app:
    build: ./Dockerfile
    container_name: hayat_app
    ports:
      - 8080:8080
    networks:
      - hayat_network
    depends_on:
      - redis
      - db
networks:
  hayat_network:
    driver: bridge
