name: Hayat-EG WorkFlow

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Build with Gradle
        run: gradle bootJar

      - name: Build & push Docker image
        uses: mr-smithers-excellent/docker-build-push@v5
        with:
          image: hassan99harera/hayat-eg
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ hayateg.DOCKER_USERNAME }}
          password: ${{ hayateg.DOCKER_PASSWORD }}
